/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package post.office.agent.rd.automation;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
